argocd-apps:
  projects:
    base:
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      sourceRepos:
      - '*'
      destinations:
      - namespace: "!argocd"
        server: '*'
      - namespace: "*"
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      permitOnlyProjectScopedClusters: false
      sourceNamespaces:
      - "base*"
