apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-monitoring-secret-fetch
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: k8s-monitoring-secrets
  data:
    # metadataPolicy to fetch all the labels in JSON format
    - secretKey: grafana
      remoteRef:
        metadataPolicy: Fetch
        key: grafana
  dataFrom:
    - extract:
        key: /grafana
