apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/CarefulNow/k8s-local.git
      revision: HEAD
      directories:
      - path: helm/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "local"
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

