apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: argocd-route
spec:
    parentRefs:
    - name: contour
      namespace: projectcontour
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /argo
      backendRefs:
      - name: argocd-server
        port: 80

