k8s-monitoring:
  cluster:
    name: mac-local
  externalServices:
    prometheus:
      hostKey: prometheus_host
      basicAuth:
        usernameKey: prometheus_user
        passwordKey: password
      secret:
        create: false
        name: grafana-k8s-monitoring-secrets
        namespace: base-grafana-k8s-monitoring
    loki:
      hostKey: loki_host
      basicAuth:
        usernameKey: loki_user
        passwordKey: password
      secret:
        create: false
        name: grafana-k8s-monitoring-secrets
        namespace: base-grafana-k8s-monitoring
    tempo:
      hostKey: tempo_host
      basicAuth:
        usernameKey: tempo_user
        passwordKey: password
      secret:
        create: false
        name: grafana-k8s-monitoring-secrets
        namespace: base-grafana-k8s-monitoring
  metrics:
    enabled: true
    alloy:
      metricsTuning:
        useIntegrationAllowList: true
    cost:
      enabled: true
    kepler:
      enabled: true
    node-exporter:
      enabled: true
    beyla:
      enabled: true
  logs:
    enabled: true
    pod_logs:
      enabled: true
    cluster_events:
      enabled: true
  traces:
    enabled: true
  receivers:
    grpc:
      enabled: true
    http:
      enabled: true
    zipkin:
      enabled: true
    grafanaCloudMetrics:
      enabled: true
  opencost:
    enabled: false
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  prometheus-operator-crds:
    enabled: true
  kepler:
    enabled: true
  alloy: { }
  alloy-events: { }
  alloy-logs: { }
  beyla:
    enabled: true